// // This file was generated by Prisma, and assumes you have installed the following:
// // npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });



/**
 * prisma.config.ts  ← PROJECT ROOT (next to package.json)
 * ─────────────────────────────────────────────────────────────────────────
 * PRISMA 7: THE NEW CONFIGURATION FILE
 * ─────────────────────────────────────────────────────────────────────────
 *
 * This file is brand new in Prisma 7. Everything that used to live in
 * the datasource block of schema.prisma now lives here.
 *
 * WHY THE SPLIT?
 *   schema.prisma   = shape of your DATA (models, relations, enums)
 *   prisma.config.ts = HOW to CONNECT (URL, migrations path, seed script)
 *
 * This separation is powerful:
 *   - This is a real TypeScript file — you can use conditional logic,
 *     import other modules, compute values dynamically.
 *   - schema.prisma is a static DSL with no runtime logic.
 *   - Different environments (dev/staging/prod) can use the same schema
 *     but different configs — just swap the config file.
 *
 * ── NEON DATABASE URLS: UNDERSTANDING THE TWO-URL PATTERN ──────────────
 *
 * Neon provides TWO connection strings for every database:
 *
 *   1. POOLED URL  (has "-pooler" in hostname)
 *      postgres://user:pass@ep-abc-pooler.us-east-2.aws.neon.tech/mydb
 *
 *      → Routes through PgBouncer (Neon's connection pooler)
 *      → Used by your Next.js app AT RUNTIME via the pg adapter
 *      → PgBouncer reuses a small pool of real Postgres connections
 *        across many serverless function invocations
 *      → Without this: each serverless invocation opens a new TCP
 *        connection. Under load, you exhaust Postgres's default
 *        limit of ~100 connections. PgBouncer prevents this.
 *
 *   2. DIRECT URL  (no "-pooler" in hostname)
 *      postgres://user:pass@ep-abc.us-east-2.aws.neon.tech/mydb
 *
 *      → Goes directly to Postgres, bypassing PgBouncer
 *      → Used by Prisma CLI for migrations and introspection ONLY
 *      → WHY: PgBouncer uses "transaction mode" pooling. This means
 *        it doesn't support advisory locks (pg_try_advisory_lock)
 *        or SET LOCAL statements — which Prisma migrate uses internally.
 *        Migrations MUST have a direct connection.
 *
 * ── PRISMA 7: url IN prisma.config.ts IS USED FOR CLI (MIGRATIONS) ─────
 *
 *   The `datasource.url` here is what the Prisma CLI reads.
 *   For migrations, you want the DIRECT URL (bypasses pooler).
 *
 *   At runtime, your app uses the POOLED URL — but that's set via
 *   the driver adapter in lib/prisma.ts, not here.
 *
 *   So the pattern is:
 *     prisma.config.ts  datasource.url → DIRECT_URL (for CLI / migrate)
 *     lib/prisma.ts     PrismaPg adapter → DATABASE_URL (for app runtime)
 *
 * ─────────────────────────────────────────────────────────────────────────
 */

import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  // Path to your schema file
  schema: "prisma/schema.prisma",

  migrations: {
    // Where migration files are written
    path: "prisma/migrations",

    // Seed script — run via: npm run db:seed  OR  npx prisma db seed
    // ⚠️ PRISMA 7 CHANGE: prisma migrate dev / migrate reset NO LONGER
    // auto-seeds. You must run prisma db seed explicitly every time.
    // This is defined here AND in package.json "prisma": { "seed": ... }
    seed: "tsx prisma/seed.ts",
  },

  datasource: {
    // ← DIRECT URL for the Prisma CLI (migrations, introspection)
    // This bypasses PgBouncer so advisory locks work during migrations.
    // If you only have one URL (e.g. local dev without pooling), just
    // use DATABASE_URL here too.
    url: env("DIRECT_URL"),
  },
});